spring:
  datasource:
    url: jdbc:mysql://localhost/academia
    username: root
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true